[package]
name = "twoes"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.0"
chumsky = { version = "1.0.0-alpha.7", features = [ "memoization" ] }
im = "15.1.0"
logos = "0.15.0"
malachite = "0.4.16"
rayon = "1.10.0"
